### ISSUE TITLE
No bold for function, if, else ... 

### ISSUE THREAD

**Issue by ZeliTheZealot** [wg030/jlcode#18] opened 2020-04-25 09:28 UTC
Everything works except that there's no bold for the keywords such as function, if, else.... Any idea? 

Thank you for your amazing work!!

**Comment by wg030** [comment] 2020-05-01 11:06
Hey @ZeliTheZealot 

that seems to be the same problem, which has already been explained here:
Duplicate of: No color in function, for, end, struct #14

**Closed as completed** 2020-05-22 10:04 UTC
